import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Hero from "../components/hero";
import StorySection from "../components/storySection";
import ServicesSection from "../components/servicesSection";
import BarberSection from "../components/barberSection";
import ContactSection from "../components/contactSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>barber app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-zinc-800 text-white">
        <Hero />
        <StorySection />
        <ServicesSection/>
        <BarberSection/>
        <ContactSection/>
      </main>
    </div>
  );
}
