import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero";
import StorySection from "../components/storySection";
import { Container } from "../components/layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>barber app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Hero />
        <StorySection />
      </main>
    </div>
  );
}
